stages:
  - build
  - test
  - deploy

# Build Stage
build:
  stage: build
  image: node:18
  script:
    - echo "Installing dependencies..."
    - npm install
  only:
    - main

# Test Stage
test:
  stage: test
  image: node:18
  script:
    - echo "Running tests..."
    - npm test || echo "Tests failed but continuing deployment"
  only:
    - main

# Deploy Stage (Adjust for AWS, Vercel, Docker, etc.)
deploy:
  stage: deploy
  image: node:18
  script:
    - echo "Deploying to server..."
    - npm run build
  only:
    - main
